name: testing setup java v5

on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test-setup-java-v5:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, windows-2025, windows-2022, macos-15, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - run: java --version